### ISSUE TITLE
Error after upgrading to MODX 2.7.0

### ISSUE THREAD

**Issue by Camo30** [Mark-H/VersionX2#105]
This error shows up in the error log after updating:

> [2018-11-30 19:40:14] (ERROR in modMenu::getSubMenus @ /www/htdocs/modx/core/model/modx/modmenu.class.php : 145) modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace versionx to the routing based system.

**Comment by Mark-H** [comment]
This is fixed in the next release (which will be either 2.2 or 3.0). Hoping to get that out soon with a bunch of other changes as well.
