### ISSUE TITLE
Feature Request - Hide from user-group

### ISSUE THREAD

**Issue by EkoOne** [Mark-H/VersionX2#108]
Need the ability to completely hide Versions from specific user-groups. A System Setting, perhaps?

Thanks.

**Comment by Mark-H** [comment]
There are system settings to toggle the tabs on the element/resource pages. Does that do what you need?

**Comment by EkoOne** [comment]
Doesn't that disable it for all user-groups? I need to hide the (Resource) Versions tab from specific groups, while keeping it for others.

**Comment by EkoOne** [comment]
I never created a system setting so I don't know what to put in the fields.

**Comment by Mark-H** [comment]
Find the system setting you want to override, copy the key, go to the user group and create a setting with the same key on the settings tab.

**Comment by EkoOne** [comment]
Ok. I assume the (VersionX) setting that controls that particular tab is under the "formtabs" section? Is that correct?
