### ISSUE TITLE
Don't work Vx2.2.1 in Modx 2.7.0

### ISSUE THREAD

**Issue by Arahort** [Mark-H/VersionX2#109]
Hi! I'm install versionx-2.2.1 in my Modx 2.7.0, but he not working :( in console have many 404 errors
http://joxi.ru/Vm6BaXJHDg1k1m
And broken buttons (save e.t.c) in admin panel :(

**Comment by Mark-H** [comment]
Check your file system. If the files it links to are there, the file permissions may be wrong on any of them or the directories they are in. If the files are not there, do a reinstall.

**Comment by Arahort** [comment]
UPD bug found, there was a problem in the incorrect path on the site, but in MODX_ASSETS_PATH I'm sorry :)
P.S. while looking for the cause of the problem, saw that people are facing overflow of the Database when there are too many version X logs and offer plugins to store the last 5 changes, it would be nice to include this setting in the component :)

**Comment by Mark-H** [comment]
Glad you found the problem.

There's already an issue for limiting the number of versions: #4
