### ISSUE TITLE
Migrate script issue [MODX 3]

### ISSUE THREAD

**Issue by Jako** [Mark-H/VersionX2#123]
The migrate script seems to have issues.

```PHP Fatal error:  Uncaught TypeError: query(): Return value must be of type xPDOIterator, xPDO\xPDOIterator returned in /.../core/components/versionx/migrate.php:47```

PHP 8.1, MODX 3.0.3

**Comment by Mark-H** [comment]
Removing the return type hint from that function should help. Looks like we've got some mixed 2.x/3.x logic in there that needs to be looked at...

**Comment by Jako** [comment]
Without the type hint the migration works fine.

**Comment by muzzwood** [comment]
Fixed in https://github.com/modmore/VersionX/commit/92f48a76af0d778164db459b911fca6741be3d71
