### ISSUE TITLE
Not translatable

### ISSUE THREAD

**Issue by Jako** [Mark-H/VersionX2#124]
In this file are a lot of not translatable english texts like: https://github.com/modmore/VersionX/blob/195811623278dbc99f4994a3dbe066f5cde4387d/assets/components/versionx/js/mgr/grid.deltas.js#L257

It would be great, if they can be added to the default lexicon.

**Comment by muzzwood** [comment]
Added in https://github.com/modmore/VersionX/commit/d149f1f889149385481e37ffbfa3bb6314f0ae95
@Jako Many of the lexicon entries weren't used anymore. In the German lexicon file, I kept the changes you made in your previous PR but there's quite a few new ones to translate now too.
Release hopefully coming later today!

**Comment by Jako** [comment]
I can add versionx to https://hosted.weblate.org/projects/modx-extras/ to make the translations a bit easier.

I have also built a [lexicon checker](https://github.com/Jako/Git-Package-Management/blob/feature/publish/core/components/gitpackagemanagement/processors/mgr/gitpackage/checklexicon.class.php) for GPM v1.

**Comment by muzzwood** [comment]
Nice work on the lexicon checker!

Weblate looks pretty cool... especially the fact it can be self-hosted. 🤔  @Mark-H ^^
