### ISSUE TITLE
ModX Cloud - Uncaught Error in migrate script

### ISSUE THREAD

**Issue by davidcmoody** [Mark-H/VersionX2#129]
` $ php core/components/versionx/migrate.php

PHP Fatal error:  Uncaught Error: Class "modmore\VersionX\VersionX" not found in /www/core/components/versionx/migrate.php:23
Stack trace:
#0 {main}
  thrown in /www/core/components/versionx/migrate.php on line 23
`

ModX 3.0.4 on ModxCloud

**Comment by Mark-H** [comment]
This suggests a potential installation error, can you try a reinstall and provide the installation log? Can you also confirm the VersionX version please?

**Comment by Mark-H** [comment]
Also does it happen in the component as well or just the migration script? #128

**Comment by davidcmoody** [comment]
Re-install fixed the issue.  Thanks for the suggestion.
