### ISSUE TITLE
Widget title and description not displaying after updated to VersionX 3.0.1-pl

### ISSUE THREAD

**Issue by SnowCreative** [Mark-H/VersionX2#130]
After updating to VersionX 3.0.1-pl, the dashboard widget is not pulling the title and description from the lexicon, so it shows up like this:

![Screen Shot 2024-04-12 at 3 30 07 PM](https://github.com/modmore/VersionX/assets/2528374/c74bc602-7217-43d7-8a61-9e676efcf65e)

**Comment by muzzwood** [comment]
Huh... I think that widget is going to need some updating for v3! 👀 
Is that still displaying records from the old table? (i.e. you don't see changes now when you save a resource?)

**Comment by SnowCreative** [comment]
Actually, it looks like the widget has been removed entirely. That legacy widget uses the table "versionx_resources," which isn't used now. Not good. There's no way to see which resources have been updated recently by all users now.

**Comment by Mark-H** [comment]
Yeah, we overlooked that in the 3.0 rebuild. It's in our tracker to re-implement, so thanks for bringing it to our attention. 

If you want to speed up the timeline on this, I'd estimate this is going to be around 3 hours of development work, so feel free to [support our open source projects](https://modmore.com/donate/) for whatever priority this is to you and we'll prioritise it accordingly. 

Of course if anyone wants to submit a PR re-adding this feature, that would also be welcomed.

**Comment by muzzwood** [comment]
Version 3.1.0-pl has a new resources widget added in. It's already available on the modmore repository and should be available on the core MODX repository sometime soon.
![Screenshot 2024-05-10 at 15-03-37 Dashboard MODX Revolution](https://github.com/modmore/VersionX/assets/5160368/91a967cc-76ff-4175-b5ad-9dd79d6dadc3)

**Comment by SnowCreative** [comment]
installed the update, and it looks great, but "View Details" is the only option when clicking on an item. "Edit Resource" (or "Update Resource") should also be an option.
![Screen Shot 2024-05-10 at 11 54 44 AM](https://github.com/modmore/VersionX/assets/2528374/f8bc9f23-bbd5-4e90-9f55-a04e39c7e67a)
