### ISSUE TITLE
Need "Edit Resource" option in dashboard widget.

### ISSUE THREAD

**Issue by SnowCreative** [Mark-H/VersionX2#132]
Installed the update, and it looks great, but "View Details" is the only option when clicking on an item. "Edit Resource" (or "Update Resource") should also be an option.
![329640584-f8bc9f23-bbd5-4e90-9f55-a04e39c7e67a](https://github.com/modmore/VersionX/assets/2528374/6f5999c3-216b-4a75-bb94-69ac7cb7cfd5)

VersionX 3.1.0

**Comment by muzzwood** [comment]
Yup, good idea 👍🏻

**Comment by muzzwood** [comment]
This has been sorted in https://github.com/modmore/VersionX/commit/eed014403e278326050d741dc243c6a4867c4b8b

**Comment by SnowCreative** [comment]
Excellent!
