### ISSUE TITLE
Versions for Files?

### ISSUE THREAD

**Issue by inreti** [Mark-H/VersionX2#71]
Would be great to have versioning for files updated via manager as well. Not sure if there is a system event for this - but the action is logged in manager actions report. 
We have a couple of projects which would benefit from this, because the LESS files (and sometimes SVG) are edited directly via the manager UI.

**Comment by Mark-H** [comment]
Yeah this is definitely out of scope for VersionX. Sounds more like @modmore/Gitify material.
