### ISSUE TITLE
Error popup on save for non-admins

### ISSUE THREAD

**Issue by sylbal** [Mark-H/VersionX2#76]
Hi,

New to VersionX and rather new to ModX. Using version 2.3.3 and VersionX-2.1.
I believe I found an issue when a user with the role "contributor" (default Modx ACL setup) is saving a resource. First save is ok, then every next save with changes, that create a version, a popup is raised, see attached.
Save and version looks to be ok but this popup is a bit of anoying for users.

Not noticed when using the admin user and desapear when desinstalling VersionX.

Regards,

Edit: sorry unable to attach image!

The popup content is:
Code 200: OK
{"success":false,"message":"Autorisation refus\u00e9e !","total":0,"data":[],"object":[]}

**Comment by jenswittmann** [comment]
I've got the same error, anything i have to check in the Access Policies? Thanks :)

**Comment by Mark-H** [comment]
This is probably related to one of the dropdowns on the tabs. Perhaps your contributor role is missing classmap or listing users permission? Try to open those combos on Versions tab and see if they load properly or not.

**Comment by sylbal** [comment]
Thank's Mark and sorry to get back so late.

This was fixed adding the 'view user' role. See #80 that gives more info.

Regards,
