### ISSUE TITLE
OnSave Resoure Type is required but empty

### ISSUE THREAD

**Issue by jgulledge19** [Mark-H/VersionX2#78]
Just updated to latest version, 2.1.1 on 2.3.3pl. After opening a Resource and editing it then click on Save the Resource Type field is empty and it is required. Select the correct option Save and refresh the page and the same error happens again. I assume that this is for filtering data not saving and the required option could be removed.

![versionx-save-error](https://cloud.githubusercontent.com/assets/671767/7661905/d90b7f36-fb24-11e4-966a-83b32c270a19.png)

Thanks for reviewing!

**Comment by Mark-H** [comment]
2.1.2 patch is now available via http://modx.com/extras/package/versionx - sorry 'bout that one!
