### ISSUE TITLE
Use of undefined constant 

### ISSUE THREAD

**Issue by inreti** [Mark-H/VersionX2#79]
With the new version 2.1.2 I get a notice in log saying: 

```
/core/components/versionx/elements/plugins/versionx.plugin.php : 36) PHP notice: Use of undefined constant nul - assumed 'nul'
```
and
```
/core/components/versionx/model/versionx.class.php : 774) PHP notice: Use of undefined constant ENT_SUBSTITUTE - assumed 'ENT_SUBSTITUTE'
```

Don't know if this is causing serious problems, but it should be corrected.

**Comment by mishantrop** [comment]
Same problem when debug = 1

**Comment by mishantrop** [comment]
From
`$path = $modx->getOption('versionx.core_path', nul, MODX_CORE_PATH . 'components/versionx/');`
To
`$path = $modx->getOption('versionx.core_path', null, MODX_CORE_PATH . 'components/versionx/');`

**Comment by Mark-H** [comment]
That was indeed fixed in https://github.com/Mark-H/VersionX2/pull/82 but looks like I never pushed a new release, sorry. Will do that right away.

**Comment by Mark-H** [comment]
2.1.3 is now available
