### ISSUE TITLE
User receives Permission Denied error message On Save Resource

### ISSUE THREAD

**Issue by jgulledge19** [Mark-H/VersionX2#80]
### Summary
User receives Permission Denied error message On Save Resource but page still saves correctly. User has limited permissions but permissions to save.

**Note:** Originally reported as MODX issue: https://github.com/modxcms/revolution/issues/12447#issuecomment-110673574 but @TheBoxer said it is a VersionX issue.
```
Code: 200 
OK {"success":false,"message":"Permission denied!","total":0,"data":[],"object":[]}
```
![on-resource-save-error](https://cloud.githubusercontent.com/assets/671767/7713136/c4a452a8-fe43-11e4-8350-75b3918fdaa5.jpg)

### Step to reproduce
 - Load these permissions into MODX: https://github.com/jgulledge19/MODX-ACL-Exports/tree/master/access-policies for a User group Context Access. ![usergroup-context-access](https://cloud.githubusercontent.com/assets/671767/7713607/e4f1aac6-fe46-11e4-85b0-db4acc07c091.png)
 - Create and assign some pages to it. Then in the same user group assign that Resource Group with the standard MODX Resource Access Policy for the mgr context. ![usergroup-resource-group-access](https://cloud.githubusercontent.com/assets/671767/7713769/cb45a356-fe47-11e4-96f8-1a43b5c52958.png)
 - Create a user assigned only to the created user group and log in with account
 - Edit a page that was assigned to the created Resource Group and then click Save.

I added the permission view_users as suggested in [#12103](https://github.com/modxcms/revolution/issues/12103) and it stopped the popup. But I do not what to give that permission to the user groups.

### Observed behavior
The error message in the photo above but the resource did save.

### Expected behavior
Save as normal. 

### Environment
MODX 2.3.3pl, nginx on MODX Cloud

Related to [#12103](https://github.com/modxcms/revolution/issues/12103)

Thanks for reviewing!

**Comment by Mark-H** [comment]
What version of VersionX?

**Comment by Mark-H** [comment]
> I added the permission view_users as suggested in #12103 and it stopped the popup. But I do not what to give that permission to the user groups.

In that case, you can't use the versionx tab because it has filter options, which depend on that core permission. 

You can get rid of the tab via the VersionX system settings. You can also set these settings on a user group or user so it's disabled by default, but enabled for full admins, for example.

**Comment by TheBoxer** [comment]
The problem is present in current master branch and it's caused using `modx-combo-user`, for example here: https://github.com/Mark-H/VersionX2/blob/master/assets/components/versionx/js/mgr/resources/panel.resources.js#L26

**Comment by jgulledge19** [comment]
Quick work around:
1. In MODX Manager, under gear icon go to  Menu
2. Expand Manage and then right click on Users
3. Change the Permission to: view_user_menu and save
4. Now add the newly created permission to: AdministratorTemplate. Go under gear icon and click on Access Control Lists. Then click on the Policy Template tab and then update the Admin Template.
5. Now assign view_user permission to all content editor Access Policies. And then assign the new permission of view_user_menu to all Access Policies that you want to have access to the Users menu item.

**Comment by sebastian-marinescu** [comment]
Thanks @jgulledge19 ! That helped. 

@Mark-H maybe this should be somehow mentioned on installation? As a little note in the install-options-dialog, what do you think?

**Comment by mrStiher** [comment]
Another quick work around is hide VersionX tab on resource editing page.

1. In MODX Manager, under gear icon go to Forms
2. Create new Profile with any title and check Active. Then right click Edit on created Profile.
3. Add 2 new Rule sets for Create and Update actions. Leave Template select empty.
4. Edit each Rule set. On Regions tab add new record with id "versionx-resource-tab", save and turn off checkbox.
5. Don't forget save Rule set.
