### ISSUE TITLE
Hide Resource Versions tab from certain users

### ISSUE THREAD

**Issue by adamwintle** [Mark-H/VersionX2#84]
This might be related to https://github.com/Mark-H/VersionX2/issues/68 and https://github.com/Mark-H/VersionX2/issues/81

We have a scenario where we'd like to hide the Versions tab from certain CMS users, and only allow User Group: Editors to access the Versions tab shown on every Resource. 

I had a look in the Manager Customisations and it doesn't seem like the Versions tab is registered in there. Is there a way to hide this tab for certain User Groups?

**Comment by Mark-H** [comment]
There are settings that control what tabs are shown (check versionx in the system settings). Add those to your user group as necessary.
