### ISSUE TITLE
Don't offer snapshot on update install

### ISSUE THREAD

**Issue by wuuti** [Mark-H/VersionX2#85]
If a new version of VersionX package is installed, it still asks for creating a snapshot - which does not make sense in an update case imho. It also seems not to respect the "versionx.enable."-settings (not sure about that, but I remember beeing asked for snapshots for elements that were not enabled in the settings. 
The creation of a snapshot should only be offered if versionx is installed freshly, not on updates.

**Comment by Mark-H** [comment]
It's not doing any harm and allows people to make sure there's a version of each resource/element in the system. When you consider future features like #4 and #30 I think it's useful to have a way for an admin to create a snapshot of everything.
