### ISSUE TITLE
Version comparison missing "Template" field?

### ISSUE THREAD

**Issue by pixelchutes** [Mark-H/VersionX2#86]
Unless I am missing something, it seems that when a Template is changed on a versioned Resource, the new (or old) Template is not reflected in the version comparison fields.

If a Template has different TV associations, those differences are present, however it appears to be missing a before / after for the Resource's assigned Template (either ID or name).

Is this something that could be added to the <kbd>Fields</kbd> tab?

**Comment by Mark-H** [comment]
Fixed in next release.
