### ISSUE TITLE
Bug: Formtabs-Settings are ignored

### ISSUE THREAD

**Issue by sebastian-marinescu** [Mark-H/VersionX2#89]
I'm only interested in versioning the content, so I set it up like this:

![image](https://cloud.githubusercontent.com/assets/3798871/13256096/95aa528a-da49-11e5-8db9-8faf70b0e535.png)

But it shows all tabs:

![image](https://cloud.githubusercontent.com/assets/3798871/13256146/c8c612a8-da49-11e5-86fd-75bcd6873b64.png)

Or am I misunderstanding the settings?

**Comment by Mark-H** [comment]
Yeah you're misunderstanding, the formtabs settings are about the "Versions" tab being shown on the forms when you edit a resource or element. 

<img width="728" alt="screen shot 2016-02-23 at 17 41 22" src="https://cloud.githubusercontent.com/assets/312944/13258878/446b5d68-da55-11e5-96c3-a31fb07fc0e4.png">

**Comment by sebastian-marinescu** [comment]
Ok, I see. Thanks Mark :+1:
