### ISSUE TITLE
"Compare To" dropdown dates are cut off.

### ISSUE THREAD

**Issue by iamdave210** [Mark-H/VersionX2#91]
The "compare to" drop-down options aren't fully visible in the manager and you can't see the dates without inspecting the element.
![pasted image at 2016_08_10 07_57 am](https://cloud.githubusercontent.com/assets/4050256/17554817/616cc81e-5ed2-11e6-881e-bc308c972b35.png)

Personally, I don't think seeing the ID there is helpful. I would rather see something like Y.m.d - username
I don't think "create" or "update" are helpful either because, except for a snapshot, they'll all be "update" other than the first one.

Just my $0.02. VersionX is awesome! A must-have extra.

**Comment by Mark-H** [comment]
Fixed the cut-off in the upcoming release.
