### ISSUE TITLE
Formtab filtering not working

### ISSUE THREAD

**Issue by mrhaw** [Mark-H/VersionX2#94]
MODX 2.5.7, mysqlnd 5.0.11-dev (SkyToaster),  PHP Version 5.6.24

Filtering works on the Extra CMP but NOT on the resource formtabs!?
And reset filter wont give back the records. 

Before:
![versionxbefore](https://user-images.githubusercontent.com/346269/27759518-7a176e72-5de7-11e7-80e9-8ed79158b179.png)

After:
![versionx](https://user-images.githubusercontent.com/346269/27759476-a60ed48a-5de6-11e7-8dff-4b9c3435ce7b.png)

I suspect filter activates Context for Web!?

**Comment by Mark-H** [comment]
Fixed in 2.2.2
